### PR TITLE
Fixed getClientInfo receiving wrong format from android

### LINKED ISSUE #647: presenceChanged callback not getting called on Android Teams app.
- [X] I have reviewed the FAQ and known issues and did not find my topic

**Please note: any submissions with insufficient reproducible information will be marked as 'Waiting for customer input' and may be closed is there is no response**

**Describe the bug**
My app that uses live presence works on Window desktop and browser but when running on my Android phone using the Teams app, the  presenceChanged event is not getting called at all for remote and local presence events.  On the Windows device (running on Edge) the presence changed events are getting called for remote and local events.

```
            _presence.on("presenceChanged", onPresenceChanged);

            await _presence.initialize(data);
```
When I call `_presence.update(data, PresenceState.online)` on Android, I get an error "The local user doesn't meet the app requirements to send a message for this object."

**To Reproduce**

> Steps to reproduce the behavior:

**Expected behavior**
Presence events are triggered on all Teams clients.

**Screenshots**

> If applicable, add screenshots to help explain your problem.

**Desktop(s) (please complete the following information):**

- OS:  Android
- Version 1416

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy S22
- OS: latest
- Browser n/a
- Version 

**Additional context**

> Add any other context about the problem here.

### PR DESCRIPTION
**Pull request by huntj88**
Mapped clientInfo format some builds of android are sending to expected clientInfo format

Fixes #647

### CODE REVIEW

File: packages/live-share/src/internals/FormatFixHostDecorator.ts [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+            return {
+                userId: clientInfo.lock,
+                roles: clientInfo._loadStates,
+                displayName: clientInfo.internalState,
+            };
+        }
+        return clientInfo;
+    }
+
+    public getFluidTenantInfo(): Promise<IFluidTenantInfo> {
```
Comment (pradeepananth) [inline packages/live-share/src/internals/FormatFixHostDecorator.ts:45]: may be TODO for base decorator class?

File: packages/live-share/src/internals/FormatFixHostDecorator.ts [hunk 2]
```diff
@@ -0,0 +1,98 @@
...
+ * @hidden
+ */
+function isAndroidClientInfoBugFormat(
+    value: any
+): value is AndroidClientInfoBugFormat {
+    return (
+        typeof value?.lock === "string" &&
+        isClientRolesResponse(value?._loadStates) &&
+        (typeof value?.internalState === "string" ||
+            value?.internalState === undefined)
```
Comment (pradeepananth) [inline packages/live-share/src/internals/FormatFixHostDecorator.ts:78]: [Readability] may be extract to a function or class giving appropriate name like "AndroidClientInfoFormatBugTypeGuard"

**Review by pradeepananth — APPROVED** [review]
left minor comments/suggestions.

File: packages/live-share/src/internals/FormatFixHostDecorator.ts (hunk 2 above)
Comment (huntj88) [reply packages/live-share/src/internals/FormatFixHostDecorator.ts:78]: Extract it more than it already is? I followed the naming convention the other type guards use, but didn't want to move it to the type guard file as this will only be used in one place

File: packages/live-share/src/internals/FormatFixHostDecorator.ts (hunk 1 above)
Comment (huntj88) [reply packages/live-share/src/internals/FormatFixHostDecorator.ts]: did the work, instead of leaving a todo

**Review by ryanbliss — APPROVED** [review]
LGTM
